"""Add source_parsed_at and composite unique to vocabols_images.

Revision ID: 0f1f848d6374
Revises: 573208da9673
Create Date: 2026-03-05 07:36:11.391205

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0f1f848d6374'
down_revision: Union[str, Sequence[str], None] = '573208da9673'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # Step 1: Add source_parsed_at as nullable
    op.add_column(
        "vocabols_images",
        sa.Column("source_parsed_at", sa.DateTime(), nullable=True),
    )

    # Step 2: Backfill source_parsed_at from parsed_vocabols.parsed_at
    op.execute("""
        UPDATE vocabols_images vi
        SET source_parsed_at = pv.parsed_at
        FROM parsed_vocabols pv
        WHERE vi.parsed_vocabol_id = pv.id
    """)

    # Step 3: Make source_parsed_at non-nullable
    op.alter_column("vocabols_images", "source_parsed_at", nullable=False)

    # Step 4: Drop old unique index and create non-unique index
    op.drop_index(
        op.f("ix_vocabols_images_parsed_vocabol_id"),
        table_name="vocabols_images",
    )
    op.create_index(
        op.f("ix_vocabols_images_parsed_vocabol_id"),
        "vocabols_images",
        ["parsed_vocabol_id"],
        unique=False,
    )

    # Step 5: Create index on source_parsed_at
    op.create_index(
        op.f("ix_vocabols_images_source_parsed_at"),
        "vocabols_images",
        ["source_parsed_at"],
        unique=False,
    )

    # Step 6: Create composite unique constraint
    op.create_unique_constraint(
        "uq_vocabol_image_url",
        "vocabols_images",
        ["parsed_vocabol_id", "source_url"],
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(
        "uq_vocabol_image_url", "vocabols_images", type_="unique"
    )
    op.drop_index(
        op.f("ix_vocabols_images_source_parsed_at"),
        table_name="vocabols_images",
    )
    op.drop_index(
        op.f("ix_vocabols_images_parsed_vocabol_id"),
        table_name="vocabols_images",
    )
    op.create_index(
        op.f("ix_vocabols_images_parsed_vocabol_id"),
        "vocabols_images",
        ["parsed_vocabol_id"],
        unique=True,
    )
    op.drop_column("vocabols_images", "source_parsed_at")
    # ### end Alembic commands ###
