"""create vocabols tables

Revision ID: 19cce6392af4
Revises: 5d5961de8165
Create Date: 2026-02-19 07:39:20.401850

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '19cce6392af4'
down_revision: Union[str, Sequence[str], None] = '5d5961de8165'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('vocabols_html_changes',
    sa.Column('entry_url_id', sa.Uuid(), nullable=False),
    sa.Column('url', sa.String(), nullable=False),
    sa.Column('new_html', sa.String(), nullable=False),
    sa.Column('new_hash', sa.String(length=64), nullable=False),
    sa.Column('old_html', sa.String(), nullable=True),
    sa.Column('old_hash', sa.String(length=64), nullable=True),
    sa.Column('change_type', sa.String(length=20), nullable=False),
    sa.Column('size_change_bytes', sa.Integer(), nullable=False),
    sa.Column('size_change_pct', sa.Float(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('reviewed_at', sa.DateTime(), nullable=True),
    sa.Column('reviewed_by', sa.String(length=50), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('detected_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['entry_url_id'], ['entry_urls.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_vocabols_html_changes_change_type'), 'vocabols_html_changes', ['change_type'], unique=False)
    op.create_index(op.f('ix_vocabols_html_changes_detected_at'), 'vocabols_html_changes', ['detected_at'], unique=False)
    op.create_index(op.f('ix_vocabols_html_changes_entry_url_id'), 'vocabols_html_changes', ['entry_url_id'], unique=False)
    op.create_index(op.f('ix_vocabols_html_changes_id'), 'vocabols_html_changes', ['id'], unique=False)
    op.create_index(op.f('ix_vocabols_html_changes_status'), 'vocabols_html_changes', ['status'], unique=False)
    op.create_index(op.f('ix_vocabols_html_changes_url'), 'vocabols_html_changes', ['url'], unique=False)
    op.create_table('vocabols_raw_html',
    sa.Column('entry_url_id', sa.Uuid(), nullable=False),
    sa.Column('url', sa.String(), nullable=False),
    sa.Column('letter', sa.String(length=1), nullable=False),
    sa.Column('raw_html', sa.String(), nullable=True),
    sa.Column('content_hash', sa.String(length=64), nullable=True),
    sa.Column('http_status_code', sa.Integer(), nullable=True),
    sa.Column('error_message', sa.String(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('collected_at', sa.DateTime(), nullable=False),
    sa.Column('last_updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['entry_url_id'], ['entry_urls.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_vocabols_raw_html_content_hash'), 'vocabols_raw_html', ['content_hash'], unique=False)
    op.create_index(op.f('ix_vocabols_raw_html_entry_url_id'), 'vocabols_raw_html', ['entry_url_id'], unique=True)
    op.create_index(op.f('ix_vocabols_raw_html_id'), 'vocabols_raw_html', ['id'], unique=False)
    op.create_index(op.f('ix_vocabols_raw_html_last_updated_at'), 'vocabols_raw_html', ['last_updated_at'], unique=False)
    op.create_index(op.f('ix_vocabols_raw_html_letter'), 'vocabols_raw_html', ['letter'], unique=False)
    op.create_index(op.f('ix_vocabols_raw_html_url'), 'vocabols_raw_html', ['url'], unique=False)
    op.alter_column('entry_urls', 'letter',
               existing_type=sa.VARCHAR(length=1),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('entry_urls', 'letter',
               existing_type=sa.VARCHAR(length=1),
               nullable=True)
    op.drop_index(op.f('ix_vocabols_raw_html_url'), table_name='vocabols_raw_html')
    op.drop_index(op.f('ix_vocabols_raw_html_letter'), table_name='vocabols_raw_html')
    op.drop_index(op.f('ix_vocabols_raw_html_last_updated_at'), table_name='vocabols_raw_html')
    op.drop_index(op.f('ix_vocabols_raw_html_id'), table_name='vocabols_raw_html')
    op.drop_index(op.f('ix_vocabols_raw_html_entry_url_id'), table_name='vocabols_raw_html')
    op.drop_index(op.f('ix_vocabols_raw_html_content_hash'), table_name='vocabols_raw_html')
    op.drop_table('vocabols_raw_html')
    op.drop_index(op.f('ix_vocabols_html_changes_url'), table_name='vocabols_html_changes')
    op.drop_index(op.f('ix_vocabols_html_changes_status'), table_name='vocabols_html_changes')
    op.drop_index(op.f('ix_vocabols_html_changes_id'), table_name='vocabols_html_changes')
    op.drop_index(op.f('ix_vocabols_html_changes_entry_url_id'), table_name='vocabols_html_changes')
    op.drop_index(op.f('ix_vocabols_html_changes_detected_at'), table_name='vocabols_html_changes')
    op.drop_index(op.f('ix_vocabols_html_changes_change_type'), table_name='vocabols_html_changes')
    op.drop_table('vocabols_html_changes')
    # ### end Alembic commands ###
