"""create_vocabols_images_table

Revision ID: 573208da9673
Revises: b64523caad32
Create Date: 2026-03-04 17:02:06.190047

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '573208da9673'
down_revision: Union[str, Sequence[str], None] = 'b64523caad32'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('vocabols_images',
    sa.Column('parsed_vocabol_id', sa.Uuid(), nullable=False),
    sa.Column('source_url', sa.String(), nullable=False),
    sa.Column('s3_key', sa.String(), nullable=False),
    sa.Column('s3_bucket', sa.String(), nullable=False),
    sa.Column('content_type', sa.String(length=50), nullable=True),
    sa.Column('size_bytes', sa.Integer(), nullable=True),
    sa.Column('content_hash', sa.String(length=64), nullable=True),
    sa.Column('collection_status', sa.String(length=20), nullable=False),
    sa.Column('error_message', sa.String(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('collected_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['parsed_vocabol_id'], ['parsed_vocabols.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_vocabols_images_collected_at'), 'vocabols_images', ['collected_at'], unique=False)
    op.create_index(op.f('ix_vocabols_images_collection_status'), 'vocabols_images', ['collection_status'], unique=False)
    op.create_index(op.f('ix_vocabols_images_content_hash'), 'vocabols_images', ['content_hash'], unique=False)
    op.create_index(op.f('ix_vocabols_images_id'), 'vocabols_images', ['id'], unique=False)
    op.create_index(op.f('ix_vocabols_images_parsed_vocabol_id'), 'vocabols_images', ['parsed_vocabol_id'], unique=True)
    op.create_index(op.f('ix_vocabols_images_s3_key'), 'vocabols_images', ['s3_key'], unique=False)
    op.create_index(op.f('ix_vocabols_images_source_url'), 'vocabols_images', ['source_url'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_vocabols_images_source_url'), table_name='vocabols_images')
    op.drop_index(op.f('ix_vocabols_images_s3_key'), table_name='vocabols_images')
    op.drop_index(op.f('ix_vocabols_images_parsed_vocabol_id'), table_name='vocabols_images')
    op.drop_index(op.f('ix_vocabols_images_id'), table_name='vocabols_images')
    op.drop_index(op.f('ix_vocabols_images_content_hash'), table_name='vocabols_images')
    op.drop_index(op.f('ix_vocabols_images_collection_status'), table_name='vocabols_images')
    op.drop_index(op.f('ix_vocabols_images_collected_at'), table_name='vocabols_images')
    op.drop_table('vocabols_images')
    # ### end Alembic commands ###
