"""add index to letter column

Revision ID: 5d5961de8165
Revises: d2406f8eff88
Create Date: 2026-02-14 14:35:05.091292

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5d5961de8165'
down_revision: Union[str, Sequence[str], None] = 'd2406f8eff88'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_entry_urls_letter'), 'entry_urls', ['letter'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_entry_urls_letter'), table_name='entry_urls')
    # ### end Alembic commands ###
