"""create parsed_vocabols table

Revision ID: b64523caad32
Revises: 19cce6392af4
Create Date: 2026-03-04 10:02:11.921615

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'b64523caad32'
down_revision: Union[str, Sequence[str], None] = '19cce6392af4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('parsed_vocabols',
    sa.Column('entry_url_id', sa.Uuid(), nullable=False),
    sa.Column('raw_html_id', sa.Uuid(), nullable=False),
    sa.Column('url', sa.String(), nullable=False),
    sa.Column('algueres_word', sa.String(), nullable=True),
    sa.Column('algueres_definition', sa.String(), nullable=True),
    sa.Column('catalan_word', sa.String(), nullable=True),
    sa.Column('catalan_definition', sa.String(), nullable=True),
    sa.Column('italian_word', sa.String(), nullable=True),
    sa.Column('italian_definition', sa.String(), nullable=True),
    sa.Column('image_urls', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('audio_urls', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('image_url_count', sa.Integer(), nullable=False),
    sa.Column('audio_url_count', sa.Integer(), nullable=False),
    sa.Column('parsing_errors', sa.String(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('parsed_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['entry_url_id'], ['entry_urls.id'], ),
    sa.ForeignKeyConstraint(['raw_html_id'], ['vocabols_raw_html.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_parsed_vocabols_algueres_word'), 'parsed_vocabols', ['algueres_word'], unique=False)
    op.create_index(op.f('ix_parsed_vocabols_audio_url_count'), 'parsed_vocabols', ['audio_url_count'], unique=False)
    op.create_index(op.f('ix_parsed_vocabols_catalan_word'), 'parsed_vocabols', ['catalan_word'], unique=False)
    op.create_index(op.f('ix_parsed_vocabols_entry_url_id'), 'parsed_vocabols', ['entry_url_id'], unique=True)
    op.create_index(op.f('ix_parsed_vocabols_id'), 'parsed_vocabols', ['id'], unique=False)
    op.create_index(op.f('ix_parsed_vocabols_image_url_count'), 'parsed_vocabols', ['image_url_count'], unique=False)
    op.create_index(op.f('ix_parsed_vocabols_italian_word'), 'parsed_vocabols', ['italian_word'], unique=False)
    op.create_index(op.f('ix_parsed_vocabols_parsed_at'), 'parsed_vocabols', ['parsed_at'], unique=False)
    op.create_index(op.f('ix_parsed_vocabols_raw_html_id'), 'parsed_vocabols', ['raw_html_id'], unique=False)
    op.create_index(op.f('ix_parsed_vocabols_url'), 'parsed_vocabols', ['url'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_parsed_vocabols_url'), table_name='parsed_vocabols')
    op.drop_index(op.f('ix_parsed_vocabols_raw_html_id'), table_name='parsed_vocabols')
    op.drop_index(op.f('ix_parsed_vocabols_parsed_at'), table_name='parsed_vocabols')
    op.drop_index(op.f('ix_parsed_vocabols_italian_word'), table_name='parsed_vocabols')
    op.drop_index(op.f('ix_parsed_vocabols_image_url_count'), table_name='parsed_vocabols')
    op.drop_index(op.f('ix_parsed_vocabols_id'), table_name='parsed_vocabols')
    op.drop_index(op.f('ix_parsed_vocabols_entry_url_id'), table_name='parsed_vocabols')
    op.drop_index(op.f('ix_parsed_vocabols_catalan_word'), table_name='parsed_vocabols')
    op.drop_index(op.f('ix_parsed_vocabols_audio_url_count'), table_name='parsed_vocabols')
    op.drop_index(op.f('ix_parsed_vocabols_algueres_word'), table_name='parsed_vocabols')
    op.drop_table('parsed_vocabols')
    # ### end Alembic commands ###
