"""create entry_urls table

Revision ID: d2406f8eff88
Revises: 
Create Date: 2026-01-25 14:58:41.208063

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd2406f8eff88'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('entry_urls',
    sa.Column('url', sa.String(), nullable=False),
    sa.Column('letter', sa.String(length=1), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('discovered_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_entry_urls_id'), 'entry_urls', ['id'], unique=False)
    op.create_index(op.f('ix_entry_urls_url'), 'entry_urls', ['url'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_entry_urls_url'), table_name='entry_urls')
    op.drop_index(op.f('ix_entry_urls_id'), table_name='entry_urls')
    op.drop_table('entry_urls')
    # ### end Alembic commands ###
